#!/usr/bin/env bash

export DEV_ENV=$(pwd)
# create basic dirctory pattern
mkdir -p personal personal/exp personal/env/python personal

# download all the resources
./run --install

# create symbolic links
ln -s ~/.dot/bin bin
ln -s ~/.dot/zsh/.zshrc .zshrc
ln -s ~/.dot/zsh/.zsh_profile .zsh_profile

# reboot
reboot
